# Generated by Django 5.0.7 on 2024-07-20 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vasapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='voice_sample',
            field=models.CharField(max_length=255),
        ),
    ]
