# Generated by Django 5.0.7 on 2024-07-22 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vasapp', '0002_alter_employee_voice_sample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeid',
            field=models.IntegerField(max_length=50, unique=True),
        ),
    ]
