# Generated by Django 5.0.7 on 2024-07-22 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vasapp', '0003_alter_employee_employeeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employeeid',
            field=models.IntegerField(unique=True),
        ),
    ]
